const cars=[
{id:1,brand:'Mercedes-Benz',name:'Mercedes-AMG GT 63',year:2026,type:'رياضية',condition:'new',price:699000,mileage:'0 كم',power:'585 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'وصل حديثاً',color:'أسود أوبسيديان',seats:'4',accel:'3.2 ث',image:'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1400&q=88'},
{id:2,brand:'Porsche',name:'Porsche Cayenne S',year:2025,type:'SUV',condition:'used',price:475000,mileage:'8,900 كم',power:'468 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'Riwaq Certified',color:'رمادي كرايون',seats:'5',accel:'4.7 ث',image:'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1400&q=88'},
{id:3,brand:'BMW',name:'BMW 760i xDrive',year:2026,type:'سيدان',condition:'new',price:589000,mileage:'0 كم',power:'536 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'Executive',color:'أخضر أوكسيد',seats:'5',accel:'4.2 ث',image:'https://images.unsplash.com/photo-1556189250-72ba954cfc2b?auto=format&fit=crop&w=1400&q=88'},
{id:4,brand:'Lexus',name:'Lexus LX 600 F Sport',year:2025,type:'SUV',condition:'used',price:515000,mileage:'12,400 كم',power:'409 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'الأكثر طلباً',color:'أبيض لؤلؤي',seats:'7',accel:'6.9 ث',image:'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1400&q=88'},
{id:5,brand:'Range Rover',name:'Range Rover Autobiography',year:2026,type:'SUV',condition:'new',price:820000,mileage:'0 كم',power:'523 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'Signature',color:'سانتوريني أسود',seats:'5',accel:'4.6 ث',image:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1400&q=88'},
{id:6,brand:'Toyota',name:'Land Cruiser GR Sport',year:2026,type:'SUV',condition:'new',price:428000,mileage:'0 كم',power:'409 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'تسليم فوري',color:'أبيض بلاتيني',seats:'7',accel:'6.8 ث',image:'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1400&q=88'},
{id:7,brand:'Mercedes-Benz',name:'Mercedes-Benz S 580',year:2025,type:'سيدان',condition:'used',price:498000,mileage:'15,100 كم',power:'503 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'Riwaq Certified',color:'فضي هاي تك',seats:'5',accel:'4.4 ث',image:'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1400&q=88'},
{id:8,brand:'Porsche',name:'Porsche 911 Carrera',year:2025,type:'كوبيه',condition:'used',price:610000,mileage:'5,600 كم',power:'388 حصان',drive:'دفع خلفي',fuel:'بنزين',badge:'Collector',color:'أخضر أوك',seats:'4',accel:'4.1 ث',image:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=88'},
{id:9,brand:'BMW',name:'BMW X7 M60i',year:2025,type:'SUV',condition:'used',price:425000,mileage:'18,600 كم',power:'523 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'عائلية فاخرة',color:'أزرق تنزانايت',seats:'7',accel:'4.7 ث',image:'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1400&q=88'},
{id:10,brand:'Lexus',name:'Lexus LC 500',year:2024,type:'كوبيه',condition:'used',price:399000,mileage:'21,000 كم',power:'471 حصان',drive:'دفع خلفي',fuel:'بنزين',badge:'V8',color:'أحمر راديانت',seats:'4',accel:'4.7 ث',image:'https://images.unsplash.com/photo-1594502184342-2e12f877aa73?auto=format&fit=crop&w=1400&q=88'},
{id:11,brand:'Range Rover',name:'Range Rover Sport P530',year:2025,type:'SUV',condition:'used',price:585000,mileage:'9,700 كم',power:'523 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'Dynamic',color:'رمادي كارباتيان',seats:'5',accel:'4.5 ث',image:'https://images.unsplash.com/photo-1626847037657-fd3622613ce3?auto=format&fit=crop&w=1400&q=88'},
{id:12,brand:'Toyota',name:'Land Cruiser VX-R',year:2025,type:'SUV',condition:'used',price:349000,mileage:'17,800 كم',power:'409 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'موثق',color:'أسود',seats:'7',accel:'6.8 ث',image:'https://images.unsplash.com/photo-1625231334168-35067f8853ed?auto=format&fit=crop&w=1400&q=88'}
];
const state={condition:'all',brand:'all',type:'all',budget:'all',visible:9,favorites:new Set(JSON.parse(localStorage.getItem('riwaq-favorites')||'[]')),compare:new Set(),finder:{step:0,use:null,budget:null,type:null}};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], format=n=>new Intl.NumberFormat('ar-SA').format(n);
function filtered(){return cars.filter(c=>(state.condition==='all'||c.condition===state.condition)&&(state.brand==='all'||c.brand===state.brand)&&(state.type==='all'||c.type===state.type)&&(state.budget==='all'||c.price<=+state.budget));}
function renderFilters(){const brands=['الكل',...new Set(cars.map(c=>c.brand))];$('#brandChips').innerHTML=brands.map((b,i)=>`<button class="chip ${i===0?'active':''}" data-chip="${i===0?'all':b}">${b}</button>`).join('');$('#brandFilter').innerHTML='<option value="all">كل الماركات</option>'+[...new Set(cars.map(c=>c.brand))].map(b=>`<option>${b}</option>`).join('');}
function renderCars(){const list=filtered(),show=list.slice(0,state.visible);$('#inventoryGrid').innerHTML=show.map((c,i)=>`<article class="car-card reveal ${i%3===1?'delay-1':i%3===2?'delay-2':''}"><div class="car-image"><img src="${c.image}" alt="${c.name}" loading="lazy"><span class="badge">${c.badge}</span><button class="card-icon fav ${state.favorites.has(c.id)?'active':''}" data-fav="${c.id}" aria-label="المفضلة">${state.favorites.has(c.id)?'♥':'♡'}</button><button class="card-icon compare ${state.compare.has(c.id)?'active':''}" data-compare="${c.id}" aria-label="المقارنة">⇄</button></div><div class="car-body"><div class="car-meta"><span>${c.brand}</span><span>${c.condition==='new'?'جديدة':'موثقة'} • ${c.year}</span></div><h3>${c.name}</h3><div class="car-specs"><span>${c.mileage}</span><span>${c.power}</span><span>${c.drive}</span></div><div class="car-price"><div><small>السعر شامل الضريبة</small><strong>${format(c.price)} ر.س</strong></div><small>من ${format(Math.round(c.price/60*1.13))} ر.س/شهر</small></div><div class="card-actions"><button data-drive="${c.id}">تجربة قيادة</button><button class="details" data-details="${c.id}">استكشف السيارة</button></div></div></article>`).join('')||'<div style="grid-column:1/-1;padding:70px;text-align:center;background:#f8f6f1"><h3>لا توجد سيارات مطابقة حالياً</h3><p>جرّب تعديل الفلاتر أو اطلب من مستشار رِواق البحث لك.</p><button class="primary-btn" data-open-concierge>اطلب مساعدة</button></div>';$('#resultCount').textContent=`${list.length} سيارة`;$('#searchCount').textContent=list.length;$('#loadMore').style.display=list.length>state.visible?'inline-flex':'none';bindDynamic();observeReveals();}
function bindDynamic(){$$('[data-fav]').forEach(b=>b.onclick=()=>toggleFav(+b.dataset.fav));$$('[data-compare]').forEach(b=>b.onclick=()=>toggleCompare(+b.dataset.compare));$$('[data-details]').forEach(b=>b.onclick=()=>openCar(+b.dataset.details));$$('[data-drive]').forEach(b=>b.onclick=()=>openForm('drive',+b.dataset.drive));$$('[data-open-concierge]').forEach(b=>b.onclick=()=>openForm('concierge'));$$('[data-open-finance]').forEach(b=>b.onclick=()=>openForm('finance'));$('[data-open-sell]').forEach(b=>b.onclick=()=>openForm('sell'));$('[data-open-drive]').forEach(b=>b.onclick=()=>openForm('drive'));}
function toggleFav(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem('riwaq-favorites',JSON.stringify([...state.favorites]));$('#favoriteCount').textContent=state.favorites.size;renderCars();toast(state.favorites.has(id)?'تمت إضافة السيارة إلى المفضلة':'تمت إزالة السيارة من المفضلة');}
function toggleCompare(id){if(state.compare.has(id)){state.compare.delete(id)}else if(state.compare.size<2){state.compare.add(id)}else{toast('يمكن مقارنة سيارتين في كل مرة');return}updateCompareUI();renderCars();}
function updateCompareUI(){const items=[...state.compare].map(id=>cars.find(c=>c.id===id));$('#compareCount').textContent=items.length;$('#mobileCompareCount').textContent=items.length;$('#compareNames').textContent=items.length?items.map(c=>c.name).join(' × '):'اختر سيارتين للمقارنة';$('#compareBar').classList.toggle('show',items.length>0);}
function openCompare(){const items=[...state.compare].map(id=>cars.find(c=>c.id===id));if(items.length<2){toast('اختر سيارتين أولاً للمقارنة');return}const rows=[['السعر',c=>`${format(c.price)} ر.س`],['الموديل',c=>c.year],['الفئة',c=>c.type],['القوة',c=>c.power],['التسارع 0–100',c=>c.accel],['الدفع',c=>c.drive],['المقاعد',c=>c.seats],['الممشى',c=>c.mileage],['الحالة',c=>c.condition==='new'?'جديدة':'مستعملة موثقة']];$('#compareModalContent').innerHTML=`<div class="compare-wrap"><small class="micro-label">RIWAQ COMPARE</small><h2>مقارنة مباشرة، بدون تشتيت.</h2><table class="compare-table"><thead><tr><th></th>${items.map(c=>`<th><img class="compare-thumb" src="${c.image}" alt="${c.name}">${c.name}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><td>${r[0]}</td>${items.map(c=>`<td><strong>${r[1](c)}</strong></td>`).join('')}</tr>`).join('')}</tbody></table></div>`;openModal('#compareModal');}
function openCar(id){const c=cars.find(x=>x.id===id);$('#carModalContent').innerHTML=`<div class="car-modal-grid"><div class="modal-image" style="background-image:url('${c.image}')"><span class="badge">${c.badge}</span></div><div class="modal-details"><small class="micro-label">${c.brand} • ${c.year}</small><h2>${c.name}</h2><p class="modal-note">${c.condition==='new'?'جديدة بالكامل وجاهزة للتسليم':'مستعملة موثقة ضمن برنامج Riwaq Certified'}</p><div class="modal-price">${format(c.price)} ر.س</div><div class="spec-grid"><div><small>الممشى</small><strong>${c.mileage}</strong></div><div><small>القوة</small><strong>${c.power}</strong></div><div><small>التسارع</small><strong>${c.accel}</strong></div><div><small>نظام الدفع</small><strong>${c.drive}</strong></div><div><small>المقاعد</small><strong>${c.seats}</strong></div><div><small>اللون</small><strong>${c.color}</strong></div></div><p class="modal-note">تتضمن السيارة تقرير فحص رِواق التفصيلي، خيارات ضمان ممتد، وخدمة التوصيل للمدن المؤهلة.</p><div class="modal-buttons three"><button class="primary-btn" onclick="closeModals();openForm('drive',${c.id})">تجربة قيادة</button><button class="outline-btn" onclick="toggleCompare(${c.id});closeModals()">قارن</button><button class="outline-btn" onclick="closeModals();openForm('reserve',${c.id})">احجز 24 ساعة</button></div><div class="reserve-note">يمكن إرسال طلب تثبيت اهتمام بالسيارة لمدة 24 ساعة — الطلب التجريبي لا يتضمن تحصيلاً مالياً.</div></div></div>`;openModal('#carModal');}
function openForm(type,id){const c=id?cars.find(x=>x.id===id):null;const cfg={drive:['حجز تجربة قيادة','اختر الموعد والمدينة وسيتواصل معك فريق رِواق لتأكيد التجربة.'],finance:['طلب عرض تمويل','أرسل بياناتك الأساسية وسنجهز لك عرضاً مبدئياً مناسباً.'],sell:['قيّم سيارتك','أدخل بيانات سيارتك للحصول على تقييم أولي سريع.'],concierge:['مستشار رِواق الشخصي','أخبرنا بما تبحث عنه وسيتولى مستشارنا ترشيح أفضل الخيارات لك.'],reserve:['طلب حجز اهتمام لمدة 24 ساعة','سجّل اهتمامك بالسيارة وسيتواصل معك الفريق لتأكيد التوفر وخطوات الحجز.']};const [title,desc]=cfg[type]||cfg.concierge;let fields=type==='sell'?`<div class="form-grid"><label>الماركة<input placeholder="مثال: تويوتا"></label><label>الموديل<input placeholder="لاند كروزر"></label><label>سنة الصنع<input type="number" placeholder="2022"></label><label>الممشى<input placeholder="45,000 كم"></label></div>`:`${c?`<label>السيارة<input value="${c.name}" readonly></label>`:''}<div class="form-grid"><label>الاسم الكامل<input placeholder="الاسم"></label><label>رقم الجوال<input placeholder="05xxxxxxxx" inputmode="tel"></label><label>المدينة<select><option>الرياض</option><option>جدة</option><option>الخبر</option><option>الدمام</option><option>مكة</option><option>أخرى</option></select></label><label>${type==='drive'?'الوقت المفضل':'الميزانية التقريبية'}<input placeholder="${type==='drive'?'مساء الخميس':'350,000 ر.س'}"></label></div>`;$('#formModalContent').innerHTML=`<form class="form-shell" id="leadForm"><small class="micro-label">RIWAQ PRIVATE CLIENT</small><h2>${title}</h2><p>${desc}</p>${fields}${type==='concierge'?'<label>ما الذي تبحث عنه؟<textarea placeholder="مثال: SUV فاخرة، 7 مقاعد، ميزانيتي حتى 450 ألف..."></textarea></label>':''}<button class="primary-btn full" type="submit">إرسال الطلب</button><small class="fine-print">بالإرسال أنت توافق على التواصل معك بخصوص هذا الطلب.</small></form>`;openModal('#formModal');$('#leadForm').onsubmit=e=>{e.preventDefault();closeModals();toast('تم استلام طلبك التجريبي بنجاح');};}
function openModal(sel){$(sel).classList.add('open');document.body.classList.add('modal-open')}function closeModals(){$$('.modal').forEach(m=>m.classList.remove('open'));document.body.classList.remove('modal-open')}function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2500)}
function renderFinder(){const box=$('#finderContent'),p=$$('.finder-progress span');p.forEach((x,i)=>x.classList.toggle('active',i<=state.finder.step));const steps=[{title:'أكثر استخدامك للسيارة؟',key:'use',opts:['يومي ومدينة','عائلة وسفر','أداء ومتعة','أعمال وتنفيذي']},{title:'ميزانيتك التقريبية؟',key:'budget',opts:['حتى 350 ألف','350–500 ألف','500–700 ألف','أكثر من 700 ألف']},{title:'أي شخصية تفضل؟',key:'type',opts:['SUV','سيدان','كوبيه','رياضية']}];if(state.finder.step<3){const s=steps[state.finder.step];box.innerHTML=`<small class="micro-label">السؤال ${state.finder.step+1} من 3</small><h3>${s.title}</h3><div class="finder-options">${s.opts.map(o=>`<button class="finder-option ${state.finder[s.key]===o?'selected':''}" data-finder="${o}">${o}</button>`).join('')}</div><div class="finder-nav"><button class="finder-back" ${state.finder.step===0?'disabled':''}>رجوع</button><small>نستخدم إجاباتك فقط لتحسين الترشيح داخل هذه الجلسة.</small></div>`;$$('[data-finder]').forEach(b=>b.onclick=()=>{state.finder[s.key]=b.dataset.finder;state.finder.step++;renderFinder()});$('.finder-back').onclick=()=>{if(state.finder.step){state.finder.step--;renderFinder()}}}else{let list=[...cars];if(state.finder.budget==='حتى 350 ألف')list=list.filter(c=>c.price<=350000);else if(state.finder.budget==='350–500 ألف')list=list.filter(c=>c.price>350000&&c.price<=500000);else if(state.finder.budget==='500–700 ألف')list=list.filter(c=>c.price>500000&&c.price<=700000);else if(state.finder.budget==='أكثر من 700 ألف')list=list.filter(c=>c.price>700000);if(state.finder.type)list=list.filter(c=>c.type===state.finder.type);if(!list.length)list=cars.slice().sort((a,b)=>Math.abs(a.price-500000)-Math.abs(b.price-500000));list=list.slice(0,3);box.innerHTML=`<div class="finder-result"><small class="micro-label">RIWAQ MATCH™ RESULT</small><h3>هذه أقرب الخيارات لك.</h3><div class="finder-result-list">${list.map(c=>`<button class="finder-result-item" data-details="${c.id}"><img src="${c.image}" alt="${c.name}"><span><strong>${c.name}</strong><small>${format(c.price)} ر.س • ${c.power}</small></span></button>`).join('')}</div><div class="finder-nav"><button class="finder-back">ابدأ من جديد</button><button class="primary-btn compact" data-open-concierge>أرسل النتيجة للمستشار</button></div></div>`;$('.finder-back').onclick=()=>{state.finder={step:0,use:null,budget:null,type:null};renderFinder()};bindDynamic();}}
const calc={price:320000,down:20,term:60,rate:.065};function updateCalc(){const principal=calc.price*(1-calc.down/100),r=calc.rate/12,p=Math.round(principal*(r*Math.pow(1+r,calc.term))/(Math.pow(1+r,calc.term)-1));$('#priceValue').textContent=`${format(calc.price)} ر.س`;$('#downValue').textContent=`${format(calc.price*calc.down/100)} ر.س`;$('#monthlyValue').innerHTML=`${format(p)} <i>ر.س / شهر</i>`}
function observeReveals(){const items=$$('.reveal:not(.visible)');if(!('IntersectionObserver'in window)){items.forEach(x=>x.classList.add('visible'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});items.forEach(x=>io.observe(x));}
function initStory(){const steps=$$('.story-step'),frame=$('#storyFrame'),imgs=["https://images.unsplash.com/photo-1485291571150-772bcfc10da5?auto=format&fit=crop&w=1400&q=90","https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1400&q=90","https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1400&q=90"];if(!('IntersectionObserver'in window))return;const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const n=+e.target.dataset.story;steps.forEach(x=>x.classList.remove('active'));e.target.classList.add('active');frame.style.backgroundImage=`url('${imgs[n]}')`}}),{rootMargin:'-35% 0px -45% 0px',threshold:0});steps.forEach(s=>io.observe(s));}

function initOwnership(){
  const select=$('#ownershipCar');
  if(!select)return;
  select.innerHTML=cars.map(c=>`<option value="${c.id}">${c.name} — ${format(c.price)} ر.س</option>`).join('');
  const update=()=>{
    const c=cars.find(x=>x.id===+select.value)||cars[0],km=+$('#kmRange').value,years=+$('#yearsRange').value;
    $('#kmValue').textContent=`${format(km)} كم`;$('#yearsValue').textContent=`${years} ${years===2?'سنتان':'سنوات'}`;
    const principal=c.price*.8,r=.065/12,n=60,finance=Math.round(principal*(r*Math.pow(1+r,n))/(Math.pow(1+r,n)-1));
    const liters=(c.type==='SUV'?12.5:c.type==='رياضية'||c.type==='كوبيه'?11.5:9.5),fuel=Math.round((km/100*liters*2.3)/12);
    const service=Math.round((c.price*(c.brand==='Toyota'?0.008:0.012))/12);
    const insurance=Math.round((c.price*.022)/12);
    const total=finance+fuel+service+insurance;
    $('#costFinance').textContent=`${format(finance)} ر.س`;$('#costFuel').textContent=`${format(fuel)} ر.س`;$('#costService').textContent=`${format(service)} ر.س`;$('#costInsurance').textContent=`${format(insurance)} ر.س`;$('#ownershipTotal').textContent=`${format(total)} ر.س / شهر`;
  };
  select.onchange=update;$('#kmRange').oninput=update;$('#yearsRange').oninput=update;
  $('#ownershipCompareBtn').onclick=()=>{const id=+select.value;if(!state.compare.has(id)&&state.compare.size>=2){toast('المقارنة ممتلئة — احذف سيارة أولاً');return}toggleCompare(id);toast('تم تحديث قائمة المقارنة')};
  update();
}
const cityData={
  riyadh:{name:'الرياض',desc:'تغطية موسعة داخل الرياض مع إمكانية تجربة قيادة منزلية للسيارات المؤهلة.',delivery:'خلال 24 ساعة',drive:'متاحة',pickup:'استلام خاص',note:'تشمل الخدمة مناطق رئيسية داخل مدينة الرياض.'},
  jeddah:{name:'جدة',desc:'تجربة شراء مرنة في جدة مع تنسيق المعاينة والتوصيل حسب توفر السيارة.',delivery:'24–48 ساعة',drive:'متاحة',pickup:'بموعد',note:'يتم تأكيد التغطية والوقت النهائي بعد اختيار السيارة.'},
  khobar:{name:'الخبر',desc:'خدمة للخبر والمدن القريبة مع تنسيق خاص للتوصيل وتجربة القيادة.',delivery:'24–48 ساعة',drive:'حسب السيارة',pickup:'بموعد',note:'بعض السيارات قد تحتاج نقلاً بين المدن قبل التجربة.'}
};
function renderCity(key='riyadh'){
  const d=cityData[key],panel=$('#cityPanel');if(!panel)return;
  $('#cityTabs button').forEach(b=>b.classList.toggle('active',b.dataset.city===key));
  panel.innerHTML=`<div class="city-panel-top"><div><small class="micro-label">RIWAQ • ${d.name}</small><h3>خدمة مصممة لمدينتك.</h3><p>${d.desc}</p></div><span class="city-status">الخدمة متاحة</span></div><div class="city-services"><div class="city-service"><span>التوصيل المتوقع</span><b>${d.delivery}</b></div><div class="city-service"><span>تجربة القيادة</span><b>${d.drive}</b></div><div class="city-service"><span>طريقة الاستلام</span><b>${d.pickup}</b></div></div><p class="modal-note">${d.note}</p><div class="city-actions"><button class="primary-btn" data-open-drive>احجز تجربة قيادة</button><button class="outline-btn" data-open-concierge>نسّق مع مستشار رِواق</button></div>`;
  bindDynamic();
}
function initCity(){
  if(!$('#cityTabs'))return;
  $('#cityTabs button').forEach(b=>b.onclick=()=>renderCity(b.dataset.city));
  $('[data-city-link]').forEach(a=>a.onclick=()=>setTimeout(()=>renderCity(a.dataset.cityLink),0));
  renderCity('riyadh');
}
function initFAQ(){ $('.faq-question').forEach(q=>q.onclick=()=>{const item=q.closest('.faq-item'),was=item.classList.contains('open');$('.faq-item').forEach(x=>x.classList.remove('open'));if(!was)item.classList.add('open')});}
function initSaveSearch(){
  const btn=$('#saveSearchBtn');if(!btn)return;
  const saved=localStorage.getItem('riwaq-saved-search');if(saved){btn.classList.add('saved');btn.textContent='★ البحث محفوظ'}
  btn.onclick=()=>{localStorage.setItem('riwaq-saved-search',JSON.stringify({condition:state.condition,brand:$('#brandFilter').value,type:$('#typeFilter').value,budget:$('#budgetFilter').value}));btn.classList.add('saved');btn.textContent='★ البحث محفوظ';toast('تم حفظ تفضيلات البحث على هذا الجهاز')};
}
function initHotspots(){ $('[data-hotspot]').forEach(h=>h.onclick=()=>{const on=h.classList.contains('active');$('[data-hotspot]').forEach(x=>x.classList.remove('active'));if(!on){h.classList.add('active');toast(h.dataset.hotspot)}}); }

function initMotion(){window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;$('#scrollProgress').style.width=`${max?scrollY/max*100:0}%`;$('#siteHeader').classList.toggle('scrolled',scrollY>70);$$('.parallax-media').forEach(el=>{const r=el.parentElement.getBoundingClientRect();el.style.transform=`scale(1.08) translateY(${r.top*.025}px)`})},{passive:true});if(matchMedia('(pointer:fine)').matches){document.addEventListener('mousemove',e=>{const g=$('#cursorGlow');g.style.opacity='1';g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'});$$('.tilt-card').forEach(card=>{card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateX(${y*-3}deg) rotateY(${x*4}deg) translateY(-3px)`});card.addEventListener('mouseleave',()=>card.style.transform='')});$$('.magnetic').forEach(btn=>{btn.addEventListener('mousemove',e=>{const r=btn.getBoundingClientRect();btn.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.09}px,${(e.clientY-r.top-r.height/2)*.09}px)`});btn.addEventListener('mouseleave',()=>btn.style.transform='')})}}
renderFilters();renderCars();renderFinder();updateCompareUI();initOwnership();initCity();initFAQ();initSaveSearch();initHotspots();observeReveals();initStory();initMotion();$('#favoriteCount').textContent=state.favorites.size;
$$('#conditionTabs button').forEach(b=>b.onclick=()=>{$$('#conditionTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.condition=b.dataset.condition;state.visible=9;renderCars()});$('#brandChips').onclick=e=>{const b=e.target.closest('[data-chip]');if(!b)return;$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.brand=b.dataset.chip;$('#brandFilter').value=state.brand;renderCars()};$('#searchCars').onclick=()=>{state.brand=$('#brandFilter').value;state.type=$('#typeFilter').value;state.budget=$('#budgetFilter').value;state.visible=9;renderCars();location.hash='inventory'};$('#resetFilters').onclick=()=>{Object.assign(state,{condition:'all',brand:'all',type:'all',budget:'all',visible:9});$('#brandFilter').value='all';$('#typeFilter').value='all';$('#budgetFilter').value='all';$$('#conditionTabs button').forEach((x,i)=>x.classList.toggle('active',i===0));renderFilters();renderCars()};$('#loadMore').onclick=()=>{state.visible+=3;renderCars()};$('.collection-card[data-type-filter]').forEach(c=>c.onclick=()=>{state.type=c.dataset.typeFilter;$('#typeFilter').value=state.type;renderCars();location.hash='inventory'});$('#openCompare').onclick=openCompare;$('#mobileCompare').onclick=openCompare;$('#compareHeaderBtn').onclick=openCompare;$('#favoriteBtn').onclick=()=>toast(state.favorites.size?`لديك ${state.favorites.size} سيارة محفوظة`:'المفضلة فارغة حالياً');$('#priceRange').oninput=e=>{calc.price=+e.target.value;updateCalc()};$('#downRange').oninput=e=>{calc.down=+e.target.value;updateCalc()};$$('#termRow button').forEach(b=>b.onclick=()=>{$$('#termRow button').forEach(x=>x.classList.remove('active'));b.classList.add('active');calc.term=+b.dataset.term;updateCalc()});$$('[data-close]').forEach(b=>b.onclick=closeModals);$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModals()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModals()});$('#menuBtn').onclick=()=>{$('.nav-links').classList.toggle('mobile-open');document.body.classList.toggle('menu-open')};$('.nav-links a').forEach(a=>a.onclick=()=>{$('.nav-links').classList.remove('mobile-open');document.body.classList.remove('menu-open')});bindDynamic();