const cars = [
 {id:1,brand:'Mercedes-Benz',name:'Mercedes-AMG GT 63',year:2026,type:'رياضية',condition:'new',price:699000,mileage:'0 كم',power:'585 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'وصل حديثاً',color:'أسود أوبسيديان',image:'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=88'},
 {id:2,brand:'Porsche',name:'Porsche Cayenne S',year:2025,type:'SUV',condition:'used',price:475000,mileage:'8,900 كم',power:'468 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'Riwaq Certified',color:'رمادي كرايون',image:'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1200&q=88'},
 {id:3,brand:'BMW',name:'BMW 760i xDrive',year:2026,type:'سيدان',condition:'new',price:589000,mileage:'0 كم',power:'536 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'Executive',color:'أخضر أوكسيد',image:'https://images.unsplash.com/photo-1556189250-72ba954cfc2b?auto=format&fit=crop&w=1200&q=88'},
 {id:4,brand:'Lexus',name:'Lexus LX 600 F Sport',year:2025,type:'SUV',condition:'used',price:515000,mileage:'12,400 كم',power:'409 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'الأكثر طلباً',color:'أبيض لؤلؤي',image:'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=88'},
 {id:5,brand:'Range Rover',name:'Range Rover Autobiography',year:2026,type:'SUV',condition:'new',price:820000,mileage:'0 كم',power:'523 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'Signature',color:'سانتوريني أسود',image:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=88'},
 {id:6,brand:'Toyota',name:'Land Cruiser GR Sport',year:2026,type:'SUV',condition:'new',price:428000,mileage:'0 كم',power:'409 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'تسليم فوري',color:'أبيض بلاتيني',image:'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1200&q=88'},
 {id:7,brand:'Mercedes-Benz',name:'Mercedes-Benz S 580',year:2025,type:'سيدان',condition:'used',price:498000,mileage:'15,100 كم',power:'503 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'Riwaq Certified',color:'فضي هاي تك',image:'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=88'},
 {id:8,brand:'Porsche',name:'Porsche 911 Carrera',year:2025,type:'كوبيه',condition:'used',price:610000,mileage:'5,600 كم',power:'388 حصان',drive:'دفع خلفي',fuel:'بنزين',badge:'Collector',color:'أخضر أوك',image:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=88'},
 {id:9,brand:'BMW',name:'BMW X7 M60i',year:2025,type:'SUV',condition:'used',price:425000,mileage:'18,600 كم',power:'523 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'عائلية فاخرة',color:'أزرق تنزانايت',image:'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=88'},
 {id:10,brand:'Lexus',name:'Lexus LC 500',year:2024,type:'كوبيه',condition:'used',price:399000,mileage:'21,000 كم',power:'471 حصان',drive:'دفع خلفي',fuel:'بنزين',badge:'V8',color:'أحمر راديانت',image:'https://images.unsplash.com/photo-1594502184342-2e12f877aa73?auto=format&fit=crop&w=1200&q=88'},
 {id:11,brand:'Range Rover',name:'Range Rover Sport P530',year:2025,type:'SUV',condition:'used',price:585000,mileage:'9,700 كم',power:'523 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'Dynamic',color:'رمادي كارباتيان',image:'https://images.unsplash.com/photo-1626847037657-fd3622613ce3?auto=format&fit=crop&w=1200&q=88'},
 {id:12,brand:'Toyota',name:'Land Cruiser VX-R',year:2025,type:'SUV',condition:'used',price:349000,mileage:'17,800 كم',power:'409 حصان',drive:'دفع رباعي',fuel:'بنزين',badge:'موثق',color:'أسود',image:'https://images.unsplash.com/photo-1625231334168-35067f8853ed?auto=format&fit=crop&w=1200&q=88'}
];
const state={condition:'all',brand:'all',type:'all',budget:'all',visible:8,favorites:new Set(JSON.parse(localStorage.getItem('riwaq-favorites')||'[]'))};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const format=n=>new Intl.NumberFormat('ar-SA').format(n);
function filters(){return cars.filter(c=>(state.condition==='all'||c.condition===state.condition)&&(state.brand==='all'||c.brand===state.brand)&&(state.type==='all'||c.type===state.type)&&(state.budget==='all'||c.price<=+state.budget));}
function renderCars(){const list=filters(), show=list.slice(0,state.visible);$('#inventoryGrid').innerHTML=show.map(c=>`<article class="car-card"><div class="car-image" style="background-image:url('${c.image}')"><span class="badge">${c.badge}</span><button class="fav ${state.favorites.has(c.id)?'active':''}" data-fav="${c.id}">${state.favorites.has(c.id)?'♥':'♡'}</button></div><div class="car-body"><div class="car-meta"><span>${c.brand}</span><span>${c.year}</span></div><h3>${c.name}</h3><div class="car-specs"><span>${c.mileage}</span><span>${c.power}</span><span>${c.drive}</span></div><div class="car-price"><div><small>السعر شامل الضريبة</small><strong>${format(c.price)} ر.س</strong></div><small>من ${format(Math.round(c.price/60*1.13))} ر.س/شهر</small></div><div class="card-actions"><button data-drive="${c.id}">تجربة قيادة</button><button class="details" data-details="${c.id}">التفاصيل</button></div></div></article>`).join('')||`<div style="grid-column:1/-1;padding:60px;text-align:center;background:#fff"><h3>لا توجد سيارات مطابقة حالياً</h3><p>جرّب تعديل الفلاتر أو اطلب من مستشار رِواق البحث لك.</p><button class="primary-btn" data-open-concierge>اطلب مساعدة</button></div>`;$('#resultCount').textContent=`${list.length} سيارات`;$('#searchCount').textContent=list.length;$('#loadMore').style.display=list.length>state.visible?'inline-block':'none'; bindDynamic();}
function renderFilters(){const brands=['الكل',...new Set(cars.map(c=>c.brand))];$('#brandChips').innerHTML=brands.map((b,i)=>`<button class="chip ${i===0?'active':''}" data-chip="${i===0?'all':b}">${b}</button>`).join('');$('#brandFilter').innerHTML=`<option value="all">كل الماركات</option>`+[...new Set(cars.map(c=>c.brand))].map(b=>`<option>${b}</option>`).join('');}
function bindDynamic(){$$('[data-fav]').forEach(b=>b.onclick=()=>toggleFav(+b.dataset.fav));$$('[data-details]').forEach(b=>b.onclick=()=>openCar(+b.dataset.details));$$('[data-drive]').forEach(b=>b.onclick=()=>openForm('drive',+b.dataset.drive));$$('[data-open-concierge]').forEach(b=>b.onclick=()=>openForm('concierge'));}
function toggleFav(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem('riwaq-favorites',JSON.stringify([...state.favorites]));$('#favoriteCount').textContent=state.favorites.size;renderCars();toast(state.favorites.has(id)?'تمت إضافة السيارة إلى المفضلة':'تمت إزالة السيارة من المفضلة');}
function openCar(id){const c=cars.find(x=>x.id===id);$('#carModalContent').innerHTML=`<div class="car-modal-grid"><div class="modal-image" style="background-image:url('${c.image}')"><span class="badge">${c.badge}</span></div><div class="modal-details"><span class="mini-label">${c.brand} • ${c.year}</span><h2>${c.name}</h2><p class="modal-note">${c.condition==='new'?'جديدة بالكامل وجاهزة للتسليم':'مستعملة موثقة ضمن برنامج Riwaq Certified'}</p><div class="modal-price">${format(c.price)} ر.س</div><div class="spec-grid"><div><small>الممشى</small><strong>${c.mileage}</strong></div><div><small>القوة</small><strong>${c.power}</strong></div><div><small>نظام الدفع</small><strong>${c.drive}</strong></div><div><small>الوقود</small><strong>${c.fuel}</strong></div><div><small>اللون</small><strong>${c.color}</strong></div><div><small>الضمان</small><strong>حسب البرنامج</strong></div></div><p class="modal-note">تتضمن السيارة تقرير فحص رِواق التفصيلي، خيارات ضمان ممتد، وخدمة التوصيل للمدن المؤهلة.</p><div class="modal-buttons"><button class="primary-btn" onclick="closeModals();openForm('drive',${c.id})">احجز تجربة قيادة</button><button class="outline-btn" onclick="closeModals();openForm('finance',${c.id})">اطلب تمويل</button></div></div></div>`;openModal('#carModal');}
function openForm(type,id){const c=id?cars.find(x=>x.id===id):null;const configs={drive:['حجز تجربة قيادة','اختر الموعد والمدينة وسيتواصل معك فريق رِواق لتأكيد التجربة.'],finance:['طلب عرض تمويل','أرسل بياناتك الأساسية وسنجهز لك عرضاً مبدئياً مناسباً.'],sell:['قيّم سيارتك','أدخل بيانات سيارتك للحصول على تقييم أولي سريع.'],concierge:['مستشار رِواق الشخصي','أخبرنا بما تبحث عنه وسيتولى مستشارنا ترشيح أفضل الخيارات لك.'],login:['تسجيل الدخول','ادخل رقم الجوال للمتابعة إلى حسابك.']};const [title,desc]=configs[type]||configs.concierge;let fields=type==='sell'?`<div class="form-grid"><label>الماركة<input placeholder="مثال: تويوتا"></label><label>الموديل<input placeholder="لاند كروزر"></label><label>سنة الصنع<input type="number" placeholder="2022"></label><label>الممشى<input placeholder="45,000 كم"></label></div>`:`${c?`<label>السيارة<input value="${c.name}" readonly></label>`:''}<div class="form-grid"><label>الاسم الكامل<input placeholder="الاسم"></label><label>رقم الجوال<input placeholder="05xxxxxxxx" inputmode="tel"></label><label>المدينة<select><option>الرياض</option><option>جدة</option><option>الخبر</option><option>الدمام</option><option>مكة</option><option>أخرى</option></select></label><label>${type==='drive'?'الوقت المفضل':'الميزانية التقريبية'}<input placeholder="${type==='drive'?'مساء الخميس':'350,000 ر.س'}"></label></div>`;$('#formModalContent').innerHTML=`<form class="form-shell" id="leadForm"><span class="mini-label">RIWAQ CONCIERGE</span><h2>${title}</h2><p>${desc}</p>${fields}${type==='concierge'?'<label>ما الذي تبحث عنه؟<textarea placeholder="مثال: SUV فاخرة، 7 مقاعد، ميزانيتي حتى 450 ألف..."></textarea></label>':''}<button class="primary-btn full" type="submit">إرسال الطلب</button><small class="fine-print">بالإرسال أنت توافق على التواصل معك بخصوص هذا الطلب.</small></form>`;openModal('#formModal');$('#leadForm').onsubmit=e=>{e.preventDefault();closeModals();toast('تم استلام طلبك التجريبي بنجاح — سيتواصل معك فريق رِواق');};}
function openModal(s){$(s).classList.add('open');$(s).setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeModals(){$$('.modal').forEach(m=>m.classList.remove('open'));document.body.style.overflow=''}function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window._tt);window._tt=setTimeout(()=>t.classList.remove('show'),2600)}
renderFilters();renderCars();$('#favoriteCount').textContent=state.favorites.size;
$$('#conditionTabs button').forEach(b=>b.onclick=()=>{$$('#conditionTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.condition=b.dataset.condition;state.visible=8;renderCars()});$('#brandChips').onclick=e=>{if(!e.target.dataset.chip)return;$$('.chip').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');state.brand=e.target.dataset.chip;$('#brandFilter').value=state.brand;renderCars()};$('#brandFilter').onchange=e=>state.brand=e.target.value;$('#typeFilter').onchange=e=>state.type=e.target.value;$('#budgetFilter').onchange=e=>state.budget=e.target.value;$('#searchCars').onclick=()=>{state.brand=$('#brandFilter').value;state.type=$('#typeFilter').value;state.budget=$('#budgetFilter').value;state.visible=8;renderCars();location.hash='inventory'};$('#resetFilters').onclick=()=>{Object.assign(state,{condition:'all',brand:'all',type:'all',budget:'all',visible:8});$('#brandFilter').value='all';$('#typeFilter').value='all';$('#budgetFilter').value='all';$$('#conditionTabs button').forEach((x,i)=>x.classList.toggle('active',i===0));renderFilters();renderCars()};$('#loadMore').onclick=()=>{state.visible+=4;renderCars()};$$('[data-close]').forEach(b=>b.onclick=closeModals);$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModals()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModals()});
$$('[data-open-finance]').forEach(b=>b.onclick=()=>openForm('finance'));$$('[data-open-drive]').forEach(b=>b.onclick=()=>openForm('drive'));$$('[data-open-sell]').forEach(b=>b.onclick=()=>openForm('sell'));$('#loginBtn').onclick=()=>openForm('login');$('#favoriteBtn').onclick=()=>toast(state.favorites.size?`لديك ${state.favorites.size} سيارة في المفضلة`:'المفضلة فارغة حالياً');
const calc={price:320000,down:20,term:60,rate:.065};function updateCalc(){const principal=calc.price*(1-calc.down/100),r=calc.rate/12,p=Math.round(principal*(r*Math.pow(1+r,calc.term))/(Math.pow(1+r,calc.term)-1));$('#priceValue').textContent=`${format(calc.price)} ر.س`;$('#downValue').textContent=`${format(calc.price*calc.down/100)} ر.س`;$('#monthlyValue').innerHTML=`${format(p)} <small>ر.س / شهر</small>`}$('#priceRange').oninput=e=>{calc.price=+e.target.value;updateCalc()};$('#downRange').oninput=e=>{calc.down=+e.target.value;updateCalc()};$$('#termRow button').forEach(b=>b.onclick=()=>{$$('#termRow button').forEach(x=>x.classList.remove('active'));b.classList.add('active');calc.term=+b.dataset.term;updateCalc()});updateCalc();
$('#menuBtn').onclick=()=>toast('استخدم الروابط في الصفحة للتنقل بين أقسام رِواق');